name: equipo5
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.5.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_signin_button: ^2.0.0
  go_router: ^14.2.7
  intl: ^0.19.0
  firebase_auth: ^5.2.1
  firebase_core: ^3.4.1
  cloud_firestore: ^5.4.1
  firebase_messaging: ^15.1.1
  timezone: ^0.9.4
  awesome_notifications: ^0.9.3+1
  google_sign_in: ^6.2.1
  logger: ^2.4.0
  provider: ^6.1.2
  uuid: ^4.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/icons/motor.png
    - assets/icons/tire.png
    - assets/icons/engine.png
    - assets/icons/brake.png
    - assets/icons/gas.png
    - assets/icons/settings.png
    - assets/icons/what.png
    - assets/icons/settings_icon.png
    - assets/icons/background_login.jpg
    - assets/icons/google_icon.png
    - assets/icons/logo.png
